name: andrew-woc

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_woc_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  web:
    build:
      dockerfile: ./Dockerfile
      network: "host"
    environment:
      - PORT=3000
      - AWS_ACCESS_KEY_ID=${BUCKET_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BUCKET_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DATABASE=${DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_woc_data: