name: andrew-woc

services:
  web:
    build:
      dockerfile: ./Dockerfile
      network: "host"
    environment:
      - PORT=3000
      - AWS_ACCESS_KEY_ID=${BUCKET_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BUCKET_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}