# File: k8s/aws-auth-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::055624675055:user/AndrewGUI
      username: AndrewGUI
      groups:
        - system:masters
    - userarn: arn:aws:iam::055624675055:user/andrewlocal
      username: andrewlocal
      groups:
        - system:masters
    - userarn: arn:aws:iam::055624675055:root
      username: root
      groups:
        - system:masters