apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-agent
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${aws_account_id}:role/eks-cloudwatch-agent-role-${local.environment}