apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent
  namespace: kube-system
  labels:
    app: cloudwatch-agent
spec:
  selector:
    matchLabels:
      app: cloudwatch-agent
  template:
    metadata:
      labels:
        app: cloudwatch-agent
    spec:
      serviceAccountName: cloudwatch-agent
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:latest
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 200m
          volumeMounts:
            - name: config-volume
              mountPath: /etc/cloudwatch-agent-config
            - name: varlog
              mountPath: /var/log
            - name: dockersock
              mountPath: /var/run/docker.sock
      volumes:
        - name: config-volume
          configMap:
            name: cloudwatch-agent-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock