---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filevault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filevault
  template:
    metadata:
      labels:
        app: filevault
    spec:
      containers:
        - name: filevault
          image: 055624675055.dkr.ecr.eu-west-2.amazonaws.com/andrewmcmahon/woc:${IMAGE_TAG}
          ports:
            - name: web
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: AWS_ACCESS_KEY_ID
              value: ${BUCKET_AWS_ACCESS_KEY_ID}
            - name: AWS_SECRET_ACCESS_KEY
              value: ${BUCKET_AWS_SECRET_ACCESS_KEY}
            - name: AWS_REGION
              value: ${AWS_REGION}
            - name: S3_BUCKET_NAME
              value: ${S3_BUCKET_NAME}
            - name: DYNAMO_DB_TABLE
              value: ${DYNAMO_DB_TABLE}
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - general
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule
