name: Terraform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call_soncarcloud:
    uses: ./.github/workflows/sonarscan.yml
    secrets:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  terraform:
    needs: call_soncarcloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set workspace name
        id: workspace
        run: |
          if [ "${{ steps.extract_branch.outputs.branch }}" == "master" ]; then
            echo "workspace=prod" >> $GITHUB_ENV
          else
            pr_number=$(echo "${{ steps.extract_branch.outputs.branch }}" | grep -oP '\d+')
            echo "workspace=pr-${pr_number}" >> $GITHUB_ENV
          fi

      - name: Initialize Terraform
        run: terraform init

#      - name: Create or select Terraform workspace
#        run: |
#          terraform workspace new ${{ env.workspace }} || terraform workspace select ${{ env.workspace }}
#
#      - name: Plan Terraform configuration
#        run: |
#          terraform plan

#      - name: Apply Terraform configuration
#        run: terraform apply -auto-approve